image: golang:1.11
stages:
  - test
  - build
  - staging
  - production


go_test:
  stage: test
  script:
    # - go test -timeout 30s ./... -run  -v -tags "test"
    - echo done

repo_push:
  stage: build
  image: docker
  services:
  - docker:dind
  script: 
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - $(aws ecr get-login --region us-east-1 --no-include-email) 
    - docker build -t ${ECR_URL}:${CI_COMMIT_SHORT_SHA} .
    - docker tag ${ECR_URL}:${CI_COMMIT_SHORT_SHA} ${ECR_URL}:latest
    - docker push ${ECR_URL}:${CI_COMMIT_SHORT_SHA}
    - docker push ${ECR_URL}:latest


staging_deploy:
  image: ruby:2.5
  stage: staging
  script:
    - echo ${AWS_PRIV_KEY} > watl_priv_key.pem
    - chmod 0400 watl_priv_key.pem
    - ssh -i watl_priv_key.pem -o "StrictHostKeyChecking no" ${INSTANCE_ADDR} 'bash -s' < ./shell/restart.sh

  only:
    - master

production_deploy:
  image: ruby:2.5
  stage: production
  script:
    - gem install dpl
  only:
    - tags